-- Fee schedules as of the 7 Sep 2026 blueprint. Every figure must be re-verified against the
-- platform's own fee page before launch; see notes. Changing a fee is a new row, never an edit.
insert into public.fee_schedules (channel, marketplace, account_type, effective_from, version, rules, source_url, notes) values
('ebay', 'GB', 'private', '2026-01-01', '2026-09-blueprint',
 '{"components":[],"vat_on_fees":false,"buyer_side":["buyer_protection_fee"]}',
 'https://www.ebay.co.uk/help/selling/fees-credits-invoices/selling-fees', 'Private sellers: no final value fee; buyer protection fee is buyer side. Verify.'),
('ebay', 'GB', 'business', '2026-01-01', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item_plus_postage","rate_bps":1290,"label":"Final value fee","category_overrides":{}},{"type":"fixed_per_order","amount_minor":30,"label":"Per order fee"},{"type":"percent","base":"item_plus_postage","rate_bps":35,"label":"Regulatory operating fee"}],"vat_on_fees":true}',
 'https://www.ebay.co.uk/help/selling/fees-credits-invoices/selling-fees', 'Business sellers. Category final value fee placeholder 12.9%; load the category table before launch. Verify.'),
('tiktok', 'GB', null, '2026-01-01', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item_plus_postage","rate_bps":900,"label":"Commission incl VAT","category_overrides":{"electronics":500,"beauty":500}}],"vat_on_fees":false}',
 'https://seller-uk.tiktok.com/', '9% commission inclusive of VAT, 5% electronics and beauty. Affiliate commission is seller-configured. Verify.'),
('amazon', 'A1F83G8C2ARO7P', null, '2026-01-01', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item_plus_postage","rate_bps":1500,"label":"Referral fee","category_overrides":{}}],"vat_on_fees":true}',
 'https://sell.amazon.co.uk/pricing', 'Referral fee 8 to 15% by category; placeholder 15%. FBA fees not modelled in v1. Verify.'),
('vinted', 'GB', 'pro', '2026-01-01', '2026-09-blueprint',
 '{"components":[],"vat_on_fees":false,"buyer_side":["buyer_protection_fee"]}',
 'https://www.vinted.co.uk/pro', 'Vinted Pro: 0% seller side. Bumps are optional paid promotion. Verify.'),
('etsy', 'GB', null, '2026-06-22', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item_plus_postage","rate_bps":650,"label":"Transaction fee"},{"type":"percent","base":"item_plus_postage","rate_bps":400,"label":"Payment processing"},{"type":"fixed_per_order","amount_minor":20,"label":"Payment processing fixed"},{"type":"percent","base":"item_plus_postage","rate_bps":48,"label":"Regulatory operating fee"},{"type":"fixed_per_listing","amount_minor":16,"label":"Listing fee"}],"vat_on_fees":true}',
 'https://www.etsy.com/uk/legal/fees', 'Listing fee is USD 0.20; GBP figure approximate. Regulatory fee 0.48% from 22 Jun 2026 per third-party guides. Verify.'),
('depop', 'GB', null, '2026-01-01', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item_plus_postage","rate_bps":290,"label":"Payment processing"},{"type":"fixed_per_order","amount_minor":30,"label":"Payment processing fixed"}],"vat_on_fees":false,"optional":[{"type":"percent","rate_bps":1200,"label":"Boosted listing"}]}',
 'https://depophelp.zendesk.com/', 'Seller side 2.9% + 30p processing. Boosting 12% only when used. Verify.'),
('onbuy', 'GB', null, '2026-01-01', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item","rate_bps":900,"label":"Commission","category_overrides":{}}],"minimum_fee_minor":25,"vat_on_fees":true}',
 'https://www.onbuy.com/gb/sell/', 'Commission by category roughly 7 to 15%; placeholder 9%. Minimum 25p per item. Verify.'),
('storefront', 'GB', null, '2026-01-01', '2026-09-blueprint',
 '{"components":[{"type":"percent","base":"item_plus_postage","rate_bps":150,"label":"Stripe UK card"},{"type":"fixed_per_order","amount_minor":20,"label":"Stripe fixed"}],"vat_on_fees":false}',
 'https://stripe.com/gb/pricing', 'Own storefront via Stripe Checkout. Verify current Stripe UK pricing.');
